###
POST http://localhost:8080/oauth2/token
Authorization: Basic bXljbGllbnRpZDpteWNsaWVudHNlY3JldA==
Content-Type:  application/x-www-form-urlencoded

grant_type=password
&client-id=myclientid
&client-secret=myclientsecret
&username=alex@gmail.com
&password=123456

# echo -n "myclientid:myclientsecret" | base64

###
POST http://localhost:8080/products
Content-Type:  application/json

{
    "name": "MESA",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui ad, adipisci illum ipsam velit et odit eaque reprehenderit ex maxime delectus dolore labore, quisquam quae tempora natus esse aliquam veniam doloremque quam minima culpa alias maiores commodi. Perferendis enim",
    "imgUrl": "https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg",
    "price": 500
}

